// can_stm32_hal.h
// STM32F767 (bxCAN) @ 1 Mbps + RX callback parsing for SDO / TPDO1(S/V/E) / Heartbeat
// Generated by ChatGPT (2025-09-19)
#pragma once

#include <stdint.h>
#include <stdbool.h>

// ---- HAL include for F7 ----
#include "stm32f7xx_hal.h"

#ifdef __cplusplus
extern "C" {
#endif

// ===== App configuration =====
// Single-node focus for parsing helpers (set to your slave Node-ID)
#ifndef APP_CANOPEN_NODE_ID
#define APP_CANOPEN_NODE_ID   0x05
#endif

// Enable or disable specific parsers in ISR
#ifndef APP_PARSE_TPDO1_SVE
#define APP_PARSE_TPDO1_SVE   1  // 6041+606C+603F
#endif
#ifndef APP_PARSE_HEARTBEAT
#define APP_PARSE_HEARTBEAT   1  // 0x700 + node
#endif
#ifndef APP_PARSE_SDO_RESP
#define APP_PARSE_SDO_RESP    1  // 0x580 + node
#endif

// ===== Pins & clocks =====
// Default: PB9 (TX), PB8 (RX) AF9 (common on F7 discovery/Nucleo). Adjust as needed.
#ifndef CAN1_TX_GPIO_PORT
#define CAN1_TX_GPIO_PORT     GPIOB
#define CAN1_TX_PIN           GPIO_PIN_9
#define CAN1_RX_GPIO_PORT     GPIOB
#define CAN1_RX_PIN           GPIO_PIN_8
#define CAN1_GPIO_AF          GPIO_AF9_CAN1
#endif

// PCLK1 frequency in Hz for bit timing. F767 typical: APB1=54MHz (SYSCLK 216MHz, APB1 div=4).
#ifndef CAN1_PCLK1_HZ
#define CAN1_PCLK1_HZ         54000000u
#endif

// ===== Public handles =====
extern CAN_HandleTypeDef hcan1;

// ===== Bring-up =====
void CAN1_BringUp_1Mbps(void);

// ===== Raw CAN send (used by od_app.c etc.) =====
int can_send(uint32_t cobid, const uint8_t* data, uint8_t len);

// ===== Minimal SDO client (download only) to satisfy od_app.c hooks =====
int sdo_write_u8 (uint8_t node, uint16_t idx, uint8_t sub, uint8_t  val);
int sdo_write_u16(uint8_t node, uint16_t idx, uint8_t sub, uint16_t val);
int sdo_write_u32(uint8_t node, uint16_t idx, uint8_t sub, uint32_t val);

// ===== Application callbacks (weak; override in your app) =====
void app_on_tpdo1_sve(uint8_t node, uint16_t status, int32_t vel_actual, uint16_t error);
void app_on_heartbeat(uint8_t node, uint8_t nmt_state);
void app_on_sdo_response(uint8_t node, uint8_t kind, uint16_t idx, uint8_t sub, uint32_t aux);

// Generic hook (still available)
void odapp_on_can_rx(uint32_t cobid, const uint8_t* data, uint8_t len);

#ifdef __cplusplus
} // extern "C"
#endif
